/* Generated by: CongoCC Parser Generator. NonTerminalCall.java */
package org.parsers.java;


public class NonTerminalCall {
    final String sourceFile;
    public final String productionName;
    final String parserClassName;
    final String location;
    final int line, column;

    public NonTerminalCall(String parserClassName, String location, String sourceFile, String productionName, int line, int column) {
        this.parserClassName = parserClassName;
        this.location = location;
        this.sourceFile = sourceFile;
        this.productionName = productionName;
        this.line = line;
        this.column = column;
    }

    public String getLocation() {
        return location;
    }

    StackTraceElement createStackTraceElement() {
        return new StackTraceElement("JavaParser", productionName, sourceFile, line);
    }

    public String toString() {
        return "at " + location + " entered " + productionName + "(" + sourceFile + ":" + line + ":" + column + ")\n";
    }

}


