includeBuild("../language-cst/e2immu-cst-api")
includeBuild("../language-cst/e2immu-cst-impl")
includeBuild("../language-cst/e2immu-cst-io")
includeBuild("e2immu-java-bytecode")
includeBuild("e2immu-java-parser")
