/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for Comment Token subclass
* by the ASTToken.java.ctl template
*/
package org.parsers.java.ast;

import org.parsers.java.*;
import static org.parsers.java.Token.TokenType.*;


public class Comment extends Token {

    public Comment(TokenType type, TokenSource tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


