/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for CTRL_Z Token subclass
* by the ASTToken.java.ftl template
*/
package org.parsers.java.ast;

import org.parsers.java.*;
import static org.parsers.java.Token.TokenType.*;


public class CTRL_Z extends Token {

    public CTRL_Z(TokenType type, JavaLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


