/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for IfStatement AST Node type
* by the ASTNode.java.ctl template
*/
package org.parsers.java.ast;

import org.parsers.java.*;
import java.util.*;
import static org.parsers.java.Token.TokenType.*;


public class IfStatement extends BaseNode implements Statement {

    public Node getElseBlock() {
        Node result = getLastChild();
        Token tok = (Token) result.previousSibling();
        if (tok.getType() == ELSE) return result;
        return null;
    }

}


