/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for IfStatement AST Node type
* by the ASTNode.java.ftl template
*/
package org.parsers.java.ast;

import org.parsers.java.*;
import java.util.*;
import org.parsers.java.Token.TokenType;
import static org.parsers.java.Token.TokenType.*;


public class IfStatement extends BaseNode implements Statement {

    public Node getElseBlock() {
        Node result = getLastChild();
        Token tok = (Token) result.previousSibling();
        if (tok.getType() == TokenType.ELSE) return result;
        return null;
        /*
        Node elseTok = firstChildOfType(TokenType.ELSE);
        return elseTok == null ? null : elseTok.nextSibling();
        */
    }

}


