/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for IntegerLiteral Token subclass
* by the ASTToken.java.ctl template
*/
package org.parsers.java.ast;

import org.parsers.java.*;
import static org.parsers.java.Token.TokenType.*;


public class IntegerLiteral extends NumericalLiteral {

    public int getValue() {
        String image = removeUnderscores(toString());
        if (image.equals("0")) return 0;
        if (image.charAt(0) != '0') return Integer.parseInt(image);
        int secondChar = image.charAt(1);
        if (secondChar == 'x' || secondChar == 'X') {
            return Integer.parseInt(image.substring(2), 16);
        }
        if (secondChar == 'b' || secondChar == 'B') {
            return Integer.parseInt(image.substring(2), 2);
        }
        return Integer.parseInt(image.substring(1), 8);
    }

    static public String removeUnderscores(String s) {
        if (s.indexOf('_') < 0) return s;
        StringBuilder buf = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            int ch = s.charAt(i);
            if (ch != '_') buf.append(ch);
        }
        return buf.toString();
    }

    public IntegerLiteral(TokenType type, TokenSource tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


