/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for Parentheses AST Node type
* by the ASTNode.java.ctl template
*/
package org.parsers.java.ast;

import org.parsers.java.*;
import java.util.*;
import static org.parsers.java.Token.TokenType.*;


public class Parentheses extends BaseNode implements PrimaryExpression {
    private Expression nestedExpression;

    //Inserted getter for nestedExpression
    public Expression getNestedExpression() {
        return nestedExpression;
    }

    //Inserted setter for nestedExpression
    public void setNestedExpression(Expression nestedExpression) {
        this.nestedExpression = nestedExpression;
    }

    // TODO: remove this @Property after jar refresh
    public boolean canBeAssignedTo() {
        return nestedExpression.canBeAssignedTo();
    }

    public boolean canBeThrown() {
        return nestedExpression.canBeThrown();
    }

}


