/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for PrimaryExpression AST Node type
* by the ASTNode.java.ctl template
*/
package org.parsers.java.ast;

import org.parsers.java.*;
import java.util.*;


public interface PrimaryExpression extends Node, Expression {
}


