/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for TernaryExpression AST Node type
* by the ASTNode.java.ctl template
*/
package org.parsers.java.ast;

import org.parsers.java.*;
import java.util.*;
import static org.parsers.java.Token.TokenType.*;


public class TernaryExpression extends BaseNode implements Expression {

    public boolean canBeThrown() {
        return ((Expression) get(2)).canBeThrown() || ((Expression) get(4)).canBeThrown();
    }

}


