/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for TypeDeclaration AST Node type
* by the ASTNode.java.ftl template
*/
package org.parsers.java.ast;

import org.parsers.java.*;
import java.util.*;


public interface TypeDeclaration extends Node, ClassOrInterfaceBodyDeclaration {
}


